//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServeurWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCLIGNE
    {
        public int ID_LIGNE { get; set; }
        public Nullable<int> ID_PIECE { get; set; }
        public Nullable<int> ID_PRODUIT { get; set; }
        public Nullable<decimal> PRIX { get; set; }
        public string DESIGNATION { get; set; }
        public Nullable<decimal> TVA { get; set; }
        public Nullable<decimal> QTE { get; set; }
    
        public virtual DOCENTETE DOCENTETE { get; set; }
        public virtual PRODUIT PRODUIT { get; set; }
    }
}
